# Generated by Django 4.2.7 on 2023-12-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pizza", "0004_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="burger",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="burger",
                to="pizza.restaurant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pizza",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pizza",
                to="pizza.restaurant",
            ),
            preserve_default=False,
        ),
    ]
