# Generated by Django 4.2.7 on 2023-12-01 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizza", "0005_burger_restaurant_pizza_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 12, 1, 17, 31, 26, 544932, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
