# Generated by Django 4.2.7 on 2024-01-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizza", "0007_restaurant_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="calories",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
